# Generated by Django 4.1 on 2022-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gelenMesajlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('mail', models.TextField(max_length=200)),
                ('telno', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
