# Generated by Django 4.1 on 2022-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0002_makaleyaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='makaleyaz',
            name='onsoz',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
