# Generated by Django 4.1 on 2022-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0003_makaleyaz_onsoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf1',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf2',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf3',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf4',
            field=models.TextField(max_length=100000),
        ),
    ]
