# Generated by Django 4.1 on 2022-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0004_alter_makaleyaz_paragraf1_alter_makaleyaz_paragraf2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf1',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf2',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf3',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='makaleyaz',
            name='paragraf4',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
