# Generated by Django 4.1 on 2022-09-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0005_alter_makaleyaz_paragraf1_alter_makaleyaz_paragraf2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makaleyaz',
            name='paragraf2',
        ),
        migrations.RemoveField(
            model_name='makaleyaz',
            name='paragraf3',
        ),
        migrations.RemoveField(
            model_name='makaleyaz',
            name='paragraf4',
        ),
    ]
