# Generated by Django 4.1 on 2022-09-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0006_remove_makaleyaz_paragraf2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makaleyaz',
            name='makaleninBenzersizIdsi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
