# Generated by Django 4.1 on 2022-09-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0009_makaleyaz_makalefotografpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makaleyaz',
            old_name='makaleFotografPath',
            new_name='makaleHtmlPath',
        ),
    ]
