# Generated by Django 4.1 on 2022-09-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0010_rename_makalefotografpath_makaleyaz_makalehtmlpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makaleyaz',
            name='makaleHtmlPath',
        ),
    ]
