# Generated by Django 4.1 on 2022-11-24 11:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMainApp', '0011_remove_makaleyaz_makalehtmlpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makaleyaz',
            old_name='makaleismi',
            new_name='yazi_ismi',
        ),
        migrations.RenameField(
            model_name='makaleyaz',
            old_name='onsoz',
            new_name='yazi_onsoz',
        ),
        migrations.RemoveField(
            model_name='makaleyaz',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='makaleyaz',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='makaleyaz',
            name='makaleninBenzersizIdsi',
        ),
        migrations.RemoveField(
            model_name='makaleyaz',
            name='paragraf1',
        ),
        migrations.AddField(
            model_name='makaleyaz',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='makaleyaz',
            name='yazi',
            field=ckeditor.fields.RichTextField(default='', max_length=99999999999999),
        ),
    ]
